name: Build with Stats

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build with stats
      run: ng build --configuration=production --stats-json

    - name: Upload stats.json
      uses: actions/upload-artifact@v3
      with:
        name: bundle-stats
        path: dist/kendo-bundle-size/stats.json
